name: tripspot_cloud
description: TripSpot (versión individual) - app funcional local, sin servicios externos por ahora.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  geolocator: ^11.0.0
  http: ^1.2.0
  crypto: ^3.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
