// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX1_jzT5XzOrOUQi0cGHiuojfOCuf-slQ',
    appId: '1:839285830998:web:19ada4c0eb6aadf419d2f7',
    messagingSenderId: '839285830998',
    projectId: 'tripspot-29371',
    authDomain: 'tripspot-29371.firebaseapp.com',
    storageBucket: 'tripspot-29371.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNwlwlu4MnWAD-S4O3iIUIKj38bh17wv8',
    appId: '1:839285830998:android:2f360dc0cb61929419d2f7',
    messagingSenderId: '839285830998',
    projectId: 'tripspot-29371',
    storageBucket: 'tripspot-29371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeOiguKpMbscsDb2wUUhye9eHI8NYwSdY',
    appId: '1:839285830998:ios:1ef5e6067cd5c3b219d2f7',
    messagingSenderId: '839285830998',
    projectId: 'tripspot-29371',
    storageBucket: 'tripspot-29371.firebasestorage.app',
    iosBundleId: 'com.example.tripspotCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeOiguKpMbscsDb2wUUhye9eHI8NYwSdY',
    appId: '1:839285830998:ios:1ef5e6067cd5c3b219d2f7',
    messagingSenderId: '839285830998',
    projectId: 'tripspot-29371',
    storageBucket: 'tripspot-29371.firebasestorage.app',
    iosBundleId: 'com.example.tripspotCloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX1_jzT5XzOrOUQi0cGHiuojfOCuf-slQ',
    appId: '1:839285830998:web:365989ee9de6c17319d2f7',
    messagingSenderId: '839285830998',
    projectId: 'tripspot-29371',
    authDomain: 'tripspot-29371.firebaseapp.com',
    storageBucket: 'tripspot-29371.firebasestorage.app',
  );
}
